# config/Security.yaml

security:
    encoders:
        App\Entity\Eleve: bcrypt

    providers:
        database_users:
            entity: { class: App\Entity\Eleve, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            logout:
                path: app.user.logout
            guard:
                authenticators:
                    - App\Security\FormLogin

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path:     /

